package edu.wheaton.simulator.statistics;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import edu.wheaton.simulator.datastructure.ElementAlreadyContainedException;
import edu.wheaton.simulator.datastructure.Grid;
import edu.wheaton.simulator.entity.Agent;
import edu.wheaton.simulator.entity.Prototype;
import edu.wheaton.simulator.entity.Trigger;
import edu.wheaton.simulator.expression.Expression;

public class Loader {

	/**
	 * The grid generated by parsing the save file
	 */
	private Grid grid; 

	/**
	 * Map of all PrototypeSnapshots for the simulation
	 * Since PrototypeSnapshots are immutable, this collection is the same for each step
	 */
	private Set<Prototype> prototypes;

	/**
	 * The name of the simulation you are loading
	 */
	private String name; 

	public Loader(){
		this.prototypes = new HashSet<Prototype>(); 
		this.name = "Default";
	}

	/**
	 * Load the contents of a file
	 * Code based on http://stackoverflow.com/questions/15906640/
	 * @param fileName The name of the file to load
	 */
	public void loadSimulation(String fileName){
		File file = new File(fileName);
		BufferedReader reader = null;
		name = fileName; 

		try {
			reader = new BufferedReader(new FileReader(file));
			
			//Instantiate the Grid
			int width = Integer.parseInt(reader.readLine()); 
			int height = Integer.parseInt(reader.readLine()); 
			grid = new Grid(width, height); 

			String readLine = reader.readLine();
			while (readLine != null) {
				//TODO: Also need to save/load ending conditions

				if(readLine.equals("AgentSnapshot")){
					//Find the appropriate prototype
					String prototypeName = reader.readLine();

					//This is an actual AgentSnapshot
					if(!prototypeName.equals("GRID")){
						Prototype parent = getPrototype(prototypeName);  

						//Create the Agent
						Agent agent = new Agent(grid, parent);

						//Get the Agent's position on the Grid
						int xpos = Integer.parseInt(reader.readLine()); 
						int ypos = Integer.parseInt(reader.readLine()); 

						//Add the agent's default fields
						readLine = reader.readLine(); 
						while(readLine.substring(0,  13).equals("FieldSnapshot")){
							String[] tokens = readLine.split(" ");
							try {
								agent.addField(tokens[1], tokens[2]);
							} catch (ElementAlreadyContainedException e) {
								System.out.println("Field already exists"); 
								e.printStackTrace();
							}
						}

						//Add the agent's triggers
						addTriggers(agent); 

						grid.addAgent(agent, xpos, ypos); 
					}
					//This is a snapshot storing grid global variables
					else{ //prototypeName.equals("GRID")
						//Skip the x and y position - doesn't matter
						reader.readLine(); 
						reader.readLine(); 

						//Add the Grid's global variables
						readLine = reader.readLine(); 
						while(readLine.substring(0,  13).equals("FieldSnapshot")){
							String[] tokens = readLine.split(" ");
							try {
								grid.addField(tokens[1], tokens[2]);
							} catch (ElementAlreadyContainedException e) {
								System.out.println("Field already exists"); 
								e.printStackTrace();
							}
						}
					}
				}
				else if(readLine.equals("PrototypeSnapshot")){
					//Parse the required prototype data
					String name = reader.readLine(); 
					Color color = new Color(Integer.parseInt(reader.readLine()));
					byte[] design = createByteArray(reader.readLine());

					//Create the prototype
					Prototype proto = new Prototype(grid, color, design, name);

					//Add the prototype's default fields
					readLine = reader.readLine(); 
					while(readLine.substring(0,  13).equals("FieldSnapshot")){
						String[] tokens = readLine.split(" ");
						try {
							proto.addField(tokens[1], tokens[2]);
						} catch (ElementAlreadyContainedException e) {
							System.out.println("Field already exists"); 
							e.printStackTrace();
						}
						readLine = reader.readLine(); 
					}

					//Add the prototype's triggers
					while(readLine.substring(0,  7).equals("Trigger")){
						String[] tokens = readLine.split("~");
						proto.addTrigger(new Trigger(tokens[1], Integer.parseInt(tokens[2]), 
								new Expression(tokens[3]), new Expression(tokens[4])));
						readLine = reader.readLine(); 
					}

					prototypes.add(proto); 
				}
				else{
					reader.readLine(); 
				}
			}
		}
		catch (FileNotFoundException e) {
			throw new RuntimeException("Could not find file: " + file.getAbsolutePath(), e);
		}
		catch (IOException e) {
			throw new RuntimeException("Could not read file: " + file.getAbsolutePath(), e);
		} finally {
			try {
				assert(reader!=null);
				reader.close();
			}
			catch (IOException e) {
				throw new RuntimeException("Could not close stream", e);
			}
		}
	}

	/**
	 * Create a byte array from a string
	 * @param s String representing a byte array in the form "010111000"
	 * @return The create byte array
	 */
	private static byte[] createByteArray(String s){
		byte[] ret = new byte[s.length()]; 

		for(int i = 0; i < s.length(); i++)
			ret[i] = (byte) s.charAt(i); 

		return ret; 
	}

	/**
	 * Add the appropriate Triggers to the specified Agent
	 * @param a The Agent to add Triggers to
	 */
	private void addTriggers(Agent a){
		Prototype parent = getPrototype(a.getPrototype().getName()); 
		List<Trigger> triggers = parent.getTriggers(); 
		for(Trigger t : triggers)
			a.addTrigger(t);
	}

	/**
	 * Get the Prototype in this class's internal list with the supplied name
	 * @param name The name of the prototype to retrieve
	 * @return The prototype with the supplied name
	 */
	private Prototype getPrototype(String name){
		Prototype ret = null; 

		for(Prototype p : prototypes)
			if(p.getName().equals(name))
				ret = p; 

		if(ret == null) 
			System.out.println("Parent Not Found");

		return ret; 
	}
}
